server:
  port: 8888


spring:
  application:
    name: gateway

  cloud:
#    gateway:
#      routes:
#      - id: r1
#        uri: http://localhost:8081/
#        predicates:
#        - Path= /customers/**
#      - id: r2
#        uri: http://localhost:8082/
#        predicates:
#        - Path= /products/**
        
    discovery:
      enabled: true
        
eureka:
  instance:
    prefer-ip-address: true
    
